brew "zsh"
brew "asdf"
brew "asciinema"
brew "coreutils"
brew "avrdude"
brew "bat"
brew "exa"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "hub"
brew "jq"
brew "minicom"
brew "neovim"
brew "pinentry-mac"
brew "qmk/qmk/qmk"
brew "pkg-config"
brew "ripgrep"
brew "shellcheck"
brew "the_silver_searcher"
brew "thefuck"
brew "trash"
brew "watchman"
brew "youtube-dl"
brew "artsy/formulas/copy_env"
brew "artsy/formulas/hokusai"
brew "d12frosted/emacs-plus/emacs-plus@26", link: false
brew "pvinis/pvinis/colortools"
brew "twpayne/taps/chezmoi"

cask "1password-cli"
cask "alfred"
cask "background-music"
cask "figma"
cask "finicky"
cask "flipper"
cask "font-iosevka"
cask "gimp"
cask "graphql-playground"
cask "hammerspoon"
cask "insomnia"
cask "java"
cask "krita"
cask "licecap"
cask "obs"
cask "postman"
cask "rambox"
cask "save-hollywood"
cask "steam"
cask "virtualbox"
cask "visual-studio-code"
cask "webtorrent"
cask "xquartz"

brew "mas"
mas "Xcode", id: 497799835
mas "Airmail", id: 918858936
mas "Things", id: 904280696
mas "Magnet", id: 441258766
mas "Gifski", id: 1351639930

mas "Pages", id: 409201541
mas "Numbers", id: 409203825
mas "Keynote", id: 409183694
