brew "chezmoi"
brew "fish"
brew "direnv"
brew "zoxide"
brew "gh"
brew "git"
brew "koekeishiya/formulae/skhd"

brew "jq"
brew "neovim"
brew "fzf"
brew "yt-dlp"
brew "pvinis/pvinis/colortools"
brew "mas"

# brew "fortune"
# brew "git-crypt"
# brew "gnupg"
# brew "gnuplot"
# brew "scrcpy"
# brew "shfmt"
# brew "solana"
# brew "tmux"
# brew "tree"

cask "font-iosevka"

cask "syncthing"
cask "tailscale"
cask "1password"
cask "1password-cli"
cask "betterdisplay"
cask "cursor"
cask "arc"
cask "dropshare"
cask "fantastical"
cask "ghostty"
cask "jordanbaird-ice"
cask "raycast"
cask "leader-key"
cask "steermouse"
cask "timemator"

cask "zen-browser"
cask "webcatalog"
cask "google-chrome"

cask "beeper"
cask "discord"
cask "viber"
cask "skype"
cask "slack"
cask "zoom"
cask "telegram-desktop"

cask "xcodes"
cask "appcleaner"
cask "chatgpt"
cask "daisydisk"
cask "gimp"
cask "latest"

cask "fork"
cask "iterm2"
cask "notion"
cask "docker"
cask "figma"
cask "around"
cask "dbeaver-community"
cask "another-redis-desktop-manager"

cask "stremio"

# cask "kopiaui"
# cask "linear-linear"
# cask "maccy"
# cask "netnewswire"
# cask "obs"
# cask "ollama"
# cask "ollamac"
# cask "parsec"
# cask "pictogram"
# cask "popclip"
# cask "rectangle-pro"
# cask "save-hollywood"
# cask "session"
# cask "shottr"
# cask "siyuan"
# cask "sonos"
# cask "spotify"
# cask "stats"
# cask "steam"
# cask "stremio"
# cask "transnomino"

mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "TV Time: Track Shows & Movies", id: 431065232

