#!/usr/bin/env deno run --allow-run


// no args: open .
// with args: open `args`


import { exec } from "https://deno.land/x/exec/mod.ts";

if (Deno.args.length === 0) {
  await exec(`open .`);
} else {
  await exec(`open ${Deno.args.join(" ")}`);
}
