#!/usr/bin/env bash


# open ~/Cloud/boxx/AABD5A86-DA77-4A7E-8E32-E7C37AF3ED2D-8654-00000146AF14EA49.mov
# /Applications/VLC.app/Contents/MacOS/VLC ~/Cloud/boxx/AABD5A86-DA77-4A7E-8E32-E7C37AF3ED2D-8654-00000146AF14EA49.mov --no-video-title-show --repeat --rate 0.6 --no-audio --video-on-top
mpv ~/Cloud/boxx/AABD5A86-DA77-4A7E-8E32-E7C37AF3ED2D-8654-00000146AF14EA49.mov --mute --loop
#  --mute --speed 0.5
# slomo
# repeat

#  --fs              fullscreen playback

#  --keep-open                      Choices: no yes always (default: no)
#  --loop                           alias for loop-file
#  --speed                          Double (0.01 to 100) (default: 1.000)
#  --video-scale-x                  Float (0 to 10000) (default: 1.000)
#  --video-scale-y                  Float (0 to 10000) (default: 1.000)
#  --video-zoom                     Float (-20 to 20) (default: 0.000)
#  --window-maximized               Flag (default: no)
#  --window-scale                   Double (0.001 to 100) (default: 1.000)
